# Default menu rows seeded when menu_items table is empty

MENU_SEED_ITEMS = [
    {
        "id": "pizza-1", "section": "pizza", "category": "🔥 Bestsellers",
        "name": "Pepperoni Fiesta",
        "description": "Classic tomato sauce, double pepperoni, mozzarella, oregano",
        "price": 499, "discount_percent": 0,
        "badge": "🏆 #1", "badge_color": "#f59e0b",
        "image_url": "https://images.unsplash.com/photo-1628840042765-356cda07504e?w=400&q=80",
        "size": "Large", "crust": "Classic", "sauce": "Tomato",
        "toppings": [{"label": "Pepperoni", "icon": "🍖", "price": 50}],
        "tags": [],
    },
    {
        "id": "pizza-2", "section": "pizza", "category": "🔥 Bestsellers",
        "name": "BBQ Chicken Blast",
        "description": "Smoky BBQ sauce, grilled chicken, red onions, bell pepper",
        "price": 549, "discount_percent": 0,
        "badge": "🔥 Hot", "badge_color": "#e63329",
        "image_url": "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400&q=80",
        "size": "Large", "crust": "Stuffed", "sauce": "BBQ",
        "toppings": [
            {"label": "Chicken", "icon": "🍗", "price": 70},
            {"label": "Onions", "icon": "🧅", "price": 20},
        ],
        "tags": [],
    },
    {
        "id": "pizza-3", "section": "pizza", "category": "🧀 Cheese Lovers",
        "name": "Four Cheese Dream",
        "description": "White sauce, mozzarella, cheddar, parmesan, gouda",
        "price": 579, "discount_percent": 0,
        "badge": "🧀 New", "badge_color": "#f97316",
        "image_url": "https://images.unsplash.com/photo-1571407970349-bc81e7e96d47?w=400&q=80",
        "size": "Large", "crust": "Stuffed", "sauce": "White",
        "toppings": [], "tags": [],
    },
    {
        "id": "pizza-4", "section": "pizza", "category": "🌶️ Spicy Specials",
        "name": "Jalapeño Inferno",
        "description": "BBQ sauce, pepperoni, jalapeños, bacon, chilli flakes",
        "price": 569, "discount_percent": 0,
        "badge": "🌶️ Spicy", "badge_color": "#dc2626",
        "image_url": "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=400&q=80",
        "size": "Large", "crust": "Thin", "sauce": "BBQ",
        "toppings": [
            {"label": "Pepperoni", "icon": "🍖", "price": 50},
            {"label": "Jalapeños", "icon": "🌶️", "price": 30},
        ],
        "tags": [],
    },
    {
        "id": "ff-101", "section": "fastfood", "category": "🍔 Burgers & Wraps",
        "name": "Classic Cheeseburger",
        "description": "Juicy beef patty, cheddar, lettuce, tomato, pickles, special sauce",
        "price": 249, "discount_percent": 0,
        "badge": "🏆 Best", "badge_color": "#f59e0b",
        "image_url": "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&q=80",
        "size": "", "crust": "", "sauce": "",
        "toppings": [], "tags": ["Beef", "Grilled"],
    },
    {
        "id": "ff-102", "section": "fastfood", "category": "🍔 Burgers & Wraps",
        "name": "Crispy Chicken Zinger",
        "description": "Spicy fried chicken fillet, coleslaw, jalapeño mayo, brioche bun",
        "price": 279, "discount_percent": 0,
        "badge": "🌶️ Spicy", "badge_color": "#dc2626",
        "image_url": "https://images.unsplash.com/photo-1606755962773-d324e0a13086?w=400&q=80",
        "size": "", "crust": "", "sauce": "",
        "toppings": [], "tags": ["Chicken", "Crispy"],
    },
    {
        "id": "ff-106", "section": "fastfood", "category": "🍟 Sides & Snacks",
        "name": "Golden French Fries",
        "description": "Crispy shoestring fries, lightly salted, served hot",
        "price": 129, "discount_percent": 0,
        "badge": "Classic", "badge_color": "#f59e0b",
        "image_url": "https://images.unsplash.com/photo-1573080496219-b080a1b07336?w=400&q=80",
        "size": "", "crust": "", "sauce": "",
        "toppings": [], "tags": ["Veg", "Shareable"],
    },
    {
        "id": "ff-110", "section": "fastfood", "category": "🍗 Wings & Chicken",
        "name": "Buffalo Wings (8 pcs)",
        "description": "Crispy wings tossed in buffalo sauce, blue cheese dip",
        "price": 349, "discount_percent": 0,
        "badge": "🔥 Hot", "badge_color": "#e63329",
        "image_url": "https://images.unsplash.com/photo-1608039829572-78524f79c4c7?w=400&q=80",
        "size": "", "crust": "", "sauce": "",
        "toppings": [], "tags": ["Chicken", "Spicy"],
    },
]
